GUHabitat-Old/Controllers/BonRetourCiterneController.cs
using CrystalDecisions.CrystalReports.Engine;
using GUHabitat.BLL;
using GUHabitat.DTO;
using GUHabitat.Models;
using GUHabitat.Reports;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace GUHabitat.Controllers
{
    public class BonRetourCiterneController : Controller
    {

        [HttpPost]
        public ActionResult ValiderTypeBon(int idTypeBonRetour)
        {
            return RedirectToAction("Ajouter", new { idTypeBonRetour = idTypeBonRetour });
        }


        // GET: BonRetourCiterne

        [HttpGet]
        public ActionResult Index(string filtreMotCle, int? page)
        {
            ModelListeBonRetourCiterne model = new ModelListeBonRetourCiterne();
            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);
            model.filtreMotCle = filtreMotCle;
            int pageSize = 10;
            int pageIndex = page.HasValue ? page.Value : 1;
            model.ListeBonRetourCiterne = BusinessGestionBonRetourCiterne.Instance.ChercherListeBon(model.filtreMotCle, idEntite, login).ToPagedList(pageIndex, pageSize);

            return View(model);


        }



        public ActionResult Acloturer(string filtreMotCle, int? page)
        {
            ModelListeBonRetourCiterne model = new ModelListeBonRetourCiterne();
            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);
            model.filtreMotCle = filtreMotCle;
            int pageSize = 10;
            int pageIndex = page.HasValue ? page.Value : 1;
            model.ListeBonRetourCiterne = BusinessGestionBonRetourCiterne.Instance.ChercherListeBonAcloturer(model.filtreMotCle, idEntite, login).ToPagedList(pageIndex, pageSize);

            ViewBag.nbInstance = BusinessGestionBonRetourCiterne.Instance.TotalCloturer();
            return View(model);

        }


        public ActionResult CloturerParDate(string date)
        {

            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            GetUser.GetUserr(login);

            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);

            BusinessGestionBonRetourCiterne.Instance.CloturerParDate(idEntite, Convert.ToDateTime(date));

            return RedirectToAction("Index");
        }




        public ActionResult EnInstance(int id)
        {
            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            GetUser.GetUserr(login);

            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);

            BusinessGestionBonRetourCiterne.Instance.EnInstance(idEntite, id);

            return RedirectToAction("Index");
        }


        public ActionResult Valider(int id)
        {
            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            GetUser.GetUserr(login);

            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);

            BusinessGestionBonRetourCiterne.Instance.Valider(idEntite, id);

            return RedirectToAction("Index");
        }



        [HttpGet]
        public ActionResult Details(int id)
        {

            ModelModifierBonRetourCiterne model = new ModelModifierBonRetourCiterne();


            BonRetourCiterneDto BonDto = BusinessGestionBonRetourCiterne.Instance.GetBonParId(id);

            if (BonDto != null)
            {
                model.id = BonDto.id;
                model.Reference = BonDto.Reference;
                model.idTypeBon = BonDto.idTypeBon;
                model.TypeBon = BonDto.TypeBon;
                model.CodeClient = BonDto.CodeClient;
                model.NomClient = BonDto.NomClient;
                model.CodeCentre = BonDto.CodeCentre;
                model.libelleCentre = BonDto.LibelleCentre;
                model.ImmtriculeCamion = BonDto.ImmtriculeCamion;
                model.DateEnvoie = BonDto.DateEnvoie;
                model.ReferenceBonChargement = BonDto.ReferenceBonChargement;
                model.PoidsVide = BonDto.PoidsVide;
                model.PoidsPlein = BonDto.PoidsPlein;
                model.PoidsGaz = BonDto.PoidsGaz;
                model.ReferencePVPesee = BonDto.ReferencePVPesee;
                model.DateRetour = BonDto.DateRetour;
                model.PoidsRetour = BonDto.PoidsRetour;
                model.PoidsVideRetour = BonDto.PoidsVideRetour;
                model.PoidsPleinRetour = BonDto.PoidsPleinRetour;

                model.PoidsGazRestant = BonDto.PoidsGazRestant;
                model.PoidsReceptionnerCentre = BonDto.PoidsReceptionnerCentre;
                model.Commentaire = BonDto.Commentaire;
                model.etat = BonDto.etat;
                model.DateLivraison = BusinessGestionBonRetourCiterne.Instance.GetDateLivraison(BonDto.id);
                model.DateLivraisonString = model.DateLivraison.Date.ToString("dd/MM/yyyy");

            };
            return View(model);

        }




        [HttpGet]
        public ActionResult Ajouter(int idTypeBonRetour)
        {
            ModelAjouterBonRetourCiterne model = new ModelAjouterBonRetourCiterne();
            model.DateEnvoie = DateTime.Now;
            model.DateRetour = DateTime.Now;
           
            string reference = GetNewCode();
            model.Reference = (reference == "1") ? "000001" : reference;
            model.idTypeBon = BusinessGestionBonRetourCiterne.Instance.GetTypeBonParId(idTypeBonRetour).id;


            if (model.idTypeBon == 1)
            {
                model.CodeClient = 0;
                model.NomClient = "Somagaz";
            }
            if (model.idTypeBon == 2)
            {

                model.CodeCentre = 0;
                model.libelleCentre  = "Somagaz";
            }
           


            return View(model);
        }



        [HttpPost]
        public ActionResult Ajouter(ModelAjouterBonRetourCiterne model)
        {


            if (ModelState.IsValid)
            {

                BonRetourCiterneDto dto = new BonRetourCiterneDto
                {


                    idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value),
                    Reference = model.Reference,
                    idTypeBon = model.idTypeBon,
                    TypeBon = model.TypeBon,
                    CodeClient = model.CodeClient,
                    NomClient = model.NomClient,
                    CodeCentre = model.CodeCentre,
                    LibelleCentre = model.libelleCentre,
                    ImmtriculeCamion = model.ImmtriculeCamion,
                    DateEnvoie = model.DateEnvoie,
                    ReferenceBonChargement = model.ReferenceBonChargement,
                    PoidsVide = model.PoidsVide,
                    PoidsPlein = model.PoidsPlein,
                    PoidsGaz = model.PoidsGaz,
                    ReferencePVPesee = model.ReferencePVPesee,
                    DateRetour = model.DateRetour,
                    PoidsRetour = model.PoidsRetour,
                    PoidsVideRetour = model.PoidsVideRetour,
                    PoidsPleinRetour = model.PoidsPleinRetour,

                    PoidsGazRestant = model.PoidsGazRestant,

                    //PoidsGazRestant = model.PoidsRetour > 0 ? (model.PoidsRetour - model.PoidsVide) : (model.PoidsVideRetour - model.PoidsPleinRetour),
                    //PoidsReceptionnerCentre = (model.PoidsGaz - model.PoidsGazRestant),

                    Commentaire = model.Commentaire,
                    etat = model.etat,




               };

                string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
                GetUser.GetUserr(login);

                var refPV = BusinessGestionBonRetourCiterne.Instance.GetBonRetourByRefPV(dto.ReferencePVPesee, dto.Reference);

                //if (model.PoidsGazRestant <= model.PoidsVide)
                //{
                //    ViewBag.MessageAjout = "Le poids de retour ne peut pas etre inferieur ou egale au poids de l'allee";
                //    return View(model);

                ////}

                if (refPV != null)
                {
                    ViewBag.MessageAjoutPV = "La reference du Bon Pesee est deja existe ";
                    return View(model);
                }

                BusinessGestionBonRetourCiterne.Instance.Ajouter(dto);
                return RedirectToAction("Index");
            }
            else
            {
                model.DateEnvoie = DateTime.Now;
                model.DateRetour = DateTime.Now;
                return View(model);
            }

        }







        [HttpGet]
        public ActionResult Modifier(int id)
        {

            ModelModifierBonRetourCiterne model = new ModelModifierBonRetourCiterne();
            model.ListeTypeBons = BusinessGestionBonRetourCiterne.Instance.GetListeTypeBon();

            BonRetourCiterneDto dto = BusinessGestionBonRetourCiterne.Instance.GetBonParId(id);
           
            if (dto != null)
            {
                model.id = dto.id;
                model.Reference = dto.Reference;
                model.idTypeBon = dto.idTypeBon;
                model.TypeBon = dto.TypeBon;
                model.CodeClient = dto.CodeClient;
                model.NomClient = dto.NomClient;
                model.CodeCentre = dto.CodeCentre;
                model.libelleCentre = dto.LibelleCentre;

GUHabitat-Old/Views/BonRetourCiterne/Acloturer.cshtml
@using PagedList.Mvc

@model GUHabitat.Models.ModelListeBonRetourCiterne
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@if (TempData["SuccessMessage"] != null)
{
    <span style="color:green;">@TempData["SuccessMessage"] </span>
}
@if (TempData["ErrorMessage"] != null)
{
    <span style="color:red;">@TempData["ErrorMessage"] </span>
}



@if (!Model.ListeBonRetourCiterne.Any())
{
    <div class="alert alert-danger">
        Pas d'instance
    </div>

}
else
{

    <h4> <span class="badge badge-success">Nombre Instance :  @ViewBag.nbInstance</span></h4>
    <br /><br />

    <div>
        <form class="form-inline" action="~/BonRetourCiterne/Acloturer">
            <div class="magin"></div>
            <div class="form-group left ">

                @Html.TextBoxFor(x => x.filtreMotCle, new { @class = "form-control left", @type = "date" })&ensp;

                @*@Html.TextBoxFor(x => x.filtreMotCle, new { @class = "form-control left", @autocomplete = "off", @placeholder = "Mot Clé" })&ensp;*@

            </div>
            <div class="form-group right ">
                <button type="submit" class="btn btn-primary right" id="buttonChercher">Chercher</button>
            </div>

        </form>


        <br />
        <div id="divAjaxContainer">

            @*<input id="checkall" type="checkbox"> Tout
                <br />
                <br />*@

            <table class="table table-bordered table-hover">
                <thead class="section-colored alert-success">
                    <tr>
                        @*<th class="text-lg-center">Cocher</th>*@
                        <th class="text-lg-center">Reference</th>
                        <th class="text-lg-center">Date</th>
                        <th class="text-lg-center">Type</th>
                        <th class="text-lg-center">Code</th>
                        <th class="text-lg-center">Concerné</th>
                        <th class="text-lg-center">Poids Depart</th>
                        <th class="text-lg-center">Poids Retour</th>
                        <th class="text-lg-center">Etat</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ListeBonRetourCiterne)
                    {
                        <tr>
                            <td class="text-lg-center">@item.Reference</td>
                            <td class="text-lg-center">@item.DateRetour.ToShortDateString()</td>
                            <td class="text-lg-center">@item.TypeBon</td>
                            @if (item.idTypeBon == 1)
                            {
                                <td class="text-lg-center">@item.CodeCentre </td>
                                <td class="text-lg-center">@item.LibelleCentre </td>
                            }
                            @if (item.idTypeBon == 2)
                            {
                                <td class="text-lg-center">@item.CodeClient </td>
                                <td class="text-lg-center">@item.NomClient </td>
                            }

                            <td class="text-lg-center">@item.PoidsGaz.ToString("0.000") </td>
                            <td class="text-lg-center">@item.PoidsGazRestant.ToString("0.000") </td>
                            <td class="text-lg-center">@item.etatString </td>

                            <td class="text-lg-center">
                                <a href="@Url.Action("Details","BonRetourCiterne", new { id = item.id})" class="btn btn-outline-info">
                                    <i class="fas fa-fw fa-info-circle"></i>
                                    Details
                                </a>

                            </td>


                        </tr>
                    }

                </tbody>

            </table>
            <div class="pager">
                Page @(Model.ListeBonRetourCiterne.PageCount < Model.ListeBonRetourCiterne.PageNumber ? 0 : Model.ListeBonRetourCiterne.PageNumber)
                / @Model.ListeBonRetourCiterne.PageCount   @Html.PagedListPager(Model.ListeBonRetourCiterne, page => Url.Action("Acloturer", new { page }))
            </div>
        </div>


        <hr />



        <div class="text-center">

            @*@if (User.IsInRole("Admin"))
                {
                    <div class="text-center">
                        <button type="submit" class="btn btn-outline-primary" id="btnPrintSelected">Clôturer</button>
                    </div>

                }*@




            @if (User.IsInRole("Admin"))
            {
                <a class="btn btn-outline-primary" href="#" data-toggle="modal" data-target="#CloturerParDate">
                    <i class="fas fa-fw fa-lock"></i>
                    Clôturer
                </a>

            }


        </div>




    </div>

}


<div class="modal fade" id="CloturerParDate" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Etês vous sûre de vouloir Clôturer les enregistrement liés à cette date : @Model.filtreMotCle</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>

                <a href="@Url.Action("CloturerParDate","BonRetourCiterne", new { date =  Model.filtreMotCle})" class="btn btn-primary">

                    Clôturer
                </a>
            </div>
        </div>
    </div>
</div>





<script>

    $(document).on('click', '#btnPrintSelected', function (event) {
        var idArray = new Array();

        $("input:checked.deleteCheckbox").each(function (i) {
            idArray[i] = $(this).attr('pkey');
        });

         var ROOT = '@Url.Content("~/")';

        $.ajax({
            type: "POST",
            url: ROOT + "/BonChargementCiterne/Selected",
            dataType: "json",
            traditional: true,
            data: {
                ids: idArray
            }


        })

            .done(function () {
                alert("success");
            })
            .fail(function () {


                $("#frmPrint").submit();
            })
        //
        event.preventDefault();
        window.location.href = ROOT +'/BonChargementCiterne/Index';

    });




    $("#checkall").change(function () {
        $(".deleteCheckbox").prop("checked", $(this).prop("checked"))
    })


</script>

GUHabitat-Old/Views/BonRetourCiterne/Imprimer.cshtml
@model GUHabitat.DTO.BonRetourCiterneDto
@{
    ViewBag.Title = "Imprimer";
}
<object data="@Url.Action("Imprimer", new { id = Model.id })" type="application/pdf" style="width: 100%; height: 600px;"></object>

GUHabitat-Old/Views/BonRetourCiterne/Index.cshtml
@using PagedList.Mvc
@{
                /**/

                ViewBag.Title = "Liste des Bons";
}
@model GUHabitat.Models.ModelListeBonRetourCiterne
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (TempData["SuccessMessage"] != null)
{
    <span style="color:green;">@TempData["SuccessMessage"] </span>
}
@if (TempData["ErrorMessage"] != null)
{
    <span style="color:red;">@TempData["ErrorMessage"] </span>
}
<br />

<div>
    <form class="form-inline" action="~/BonRetourCiterne/Index">
        <div class="row">

            <div class="magin"></div>
            <div class="form-group left ">

                @Html.TextBoxFor(x => x.filtreMotCle, new { @class = "form-control left", @autocomplete = "off", @placeholder = "Mot Clé" })&ensp;

            </div>
            <div class="form-group right ">
                <button type="submit" class="btn btn-primary right" id="buttonChercher">Chercher</button>
            </div>
        </div>
    </form>
    <br />
    <div id="divAjaxContainer">
        <div class="table-responsive">
            <table class="table table-bordered table-hover">
                <thead class="section-colored alert-success">
                    <tr>
                        <th class="text-lg-center">Reference</th>
                        <th class="text-lg-center">Date</th>
                        <th class="text-lg-center">Type</th>
                        <th class="text-lg-center">Code</th>
                        <th class="text-lg-center">Concerné</th>
                        <th class="text-lg-center">Poids Depart</th>
                        <th class="text-lg-center">Poids Retour</th>
                        <th class="text-lg-center">Etat</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ListeBonRetourCiterne)
                    {
                    <tr>
                        <td class="text-lg-center">@item.Reference</td>
                        <td class="text-lg-center">@item.DateRetour.ToShortDateString()</td>
                        <td class="text-lg-center">@item.TypeBon</td>
                        @if (item.idTypeBon == 1)
                        {
                            <td class="text-lg-center">@item.CodeCentre </td>
                            <td class="text-lg-center">@item.LibelleCentre </td>
                        }
                        @if (item.idTypeBon == 2)
                        {
                            <td class="text-lg-center">@item.CodeClient </td>
                            <td class="text-lg-center">@item.NomClient </td>
                        }

                        <td class="text-lg-center">@item.PoidsGaz.ToString("0.000") </td>
                        <td class="text-lg-center">@item.PoidsGazRestant.ToString("0.000") </td>
                        <td class="text-lg-center">@item.etatString </td>

                        <td class="text-lg-center">
                            <a href="@Url.Action("Details","BonRetourCiterne", new { id = item.id})" class="btn btn-outline-info">
                                <i class="fas fa-fw fa-info-circle"></i>
                                Details
                            </a>

                        </td>



                    </tr>
                    }

                </tbody>

            </table>
        </div>
        <div class="pager">
            Page @(Model.ListeBonRetourCiterne.PageCount < Model.ListeBonRetourCiterne.PageNumber ? 0 : Model.ListeBonRetourCiterne.PageNumber)
            / @Model.ListeBonRetourCiterne.PageCount   @Html.PagedListPager(Model.ListeBonRetourCiterne, page => Url.Action("Index", new { page, filtreMotCle = Model.filtreMotCle }))
        </div>
    </div>

</div>





@*<script>
        $(document).ready(function () {
            toastr.success("Test");
        });
    </script>*@