GUHabitat-Old/Controllers/SortieController.cs
using GUHabitat.BLL;
using GUHabitat.DTO;
using GUHabitat.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace GUHabitat.Controllers
{
    public class SortieController : Controller
    {

        [HttpPost]
        public ActionResult ValiderTypeSortie(int idTypeSortie)
        {
            return RedirectToAction("Ajouter", new { idTypeSortie = idTypeSortie });
        }

        // GET: Sortie
        public ActionResult Index(string filtreMotCle, int? page)
        {
            ModelListeSortie model = new ModelListeSortie();
            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);
            model.filtreMotCle = filtreMotCle;
            int pageSize = 10;
            int pageIndex = page.HasValue ? page.Value : 1;
            model.ListeSortie = BusinessGestionSortie.Instance.ChercherListeSortie(model.filtreMotCle, idEntite, login).ToPagedList(pageIndex, pageSize);

            return View(model);


        }



        [HttpGet]
        public ActionResult Acloturer(string filtreMotCle, int? page)
        {
            ModelListeSortie model = new ModelListeSortie();
            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);
            model.filtreMotCle = filtreMotCle;
            int pageSize = 10;
            int pageIndex = page.HasValue ? page.Value : 1;
            model.ListeSortie = BusinessGestionSortie.Instance.ChercherListeSortieCloturer(model.filtreMotCle, idEntite, login).ToPagedList(pageIndex, pageSize);

            ViewBag.nbInstance = BusinessGestionSortie.Instance.TotalCloturer();

            return View(model);


        }


        [HttpGet]
        public ActionResult Valider(string filtreMotCle, int? page)
        {
            ModelListeSortie model = new ModelListeSortie();
            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);
            model.filtreMotCle = filtreMotCle;
            int pageSize = 10;
            int pageIndex = page.HasValue ? page.Value : 1;
            model.ListeSortie = BusinessGestionSortie.Instance.ChercherListeSortieValider(model.filtreMotCle, idEntite, login).ToPagedList(pageIndex, pageSize);

            ViewBag.nbInstance = BusinessGestionSortie.Instance.TotalValider();

            return View(model);


        }


        public void SelectedValider(int[] ids)
        {
            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            GetUser.GetUserr(login);

            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);


            BusinessGestionSortie.Instance.Valider(idEntite,ids);
        }


        public void Selected(int[] ids)
        {
            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            GetUser.GetUserr(login);

            BusinessGestionSortie.Instance.Cloturer(ids);
        }




        public ActionResult EnInstance(int id)
        {


            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            GetUser.GetUserr(login);

            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);

            BusinessGestionSortie.Instance.EnInstance(idEntite, id);

            return RedirectToAction("Index");
        }

        public ActionResult ValiderParDate(string date)
        {

            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            GetUser.GetUserr(login);

            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);

            BusinessGestionSortie.Instance.Valider(idEntite,Convert.ToDateTime(date));

            return RedirectToAction("Index");
        }



        public ActionResult CloturerParDate(string date)
        {

            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            GetUser.GetUserr(login);

            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);

            BusinessGestionSortie.Instance.CloturerParDate(idEntite, Convert.ToDateTime(date));

            return RedirectToAction("Index");
        }



        [HttpGet]
        public ActionResult Details(int id)
        {

            ModelModifierSortie model = new ModelModifierSortie();


            SortieDto dto = BusinessGestionSortie.Instance.GetSortieParId(id);

            if (dto != null)
            {
                model.id = dto.id;
                model.Reference = dto.Reference;
                model.ReferenceTypeSortie = dto.ReferenceTypeSortie;
                model.NumeroFacture = dto.NumeroFacture;
                model.Client = dto.Client;
                model.Employe = dto.Employe;
                model.Date = dto.Date;
                model.idTypeSortie = dto.idTypeSortie;
                model.TypeSortie = dto.TypeSortie;

                model.B12 = dto.B12;
                model.B9 = dto.B9;
                model.B6R = dto.B6R;
                model.B6V = dto.B6V;
                model.B3 = dto.B3;
                model.B35 = dto.B35;
                model.Presentoir = dto.Presentoir;



                model.Commentaire = dto.Commentaires;
                model.etat = dto.etat;


            };
            return View(model);

        }






        [HttpGet]
        public ActionResult Ajouter(int idTypeSortie)
        {
            ModelAjouterSortie model = new ModelAjouterSortie();
            model.Date = DateTime.Now;

            string reference = GetNewCode();
            model.Reference = (reference == "1") ? "000001" : reference;
           
            model.idTypeSortie = BusinessGestionSortie.Instance.GetTypeSortieParId(idTypeSortie).id;
            //if (model.idTypeSortie == 2 )
            //{

            //    model.Employe = 0;
               
            //}

            //if (model.idTypeSortie != 2)
            //{
            //    model.Client = 0;
               
            //}
            return View(model);
        }


        [HttpPost]
        public ActionResult Ajouter(ModelAjouterSortie model)
        {


            if (ModelState.IsValid)
            {

                SortieDto dto = new SortieDto
                {
                   
                    Reference = model.Reference,
                    ReferenceTypeSortie = model.ReferenceTypeSortie,
                    NumeroFacture = model.NumeroFacture,
                    Client = model.Client,
                    Employe = model.Employe,
                    Date = model.Date,
                    idTypeSortie = model.idTypeSortie,
                   
                    B12 = model.B12,
                    B9 = model.B9,
                    B6R = model.B6R,
                    B6V = model.B6V,
                    B3 = model.B3,
                    B35 = model.B35,
                    Presentoir = model.Presentoir,

                    Commentaires = model.Commentaire,



                };

                string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
                GetUser.GetUserr(login);


                //var nbrefiche = BusinessGestionSortie.Instance.VerifierExistFiche(model.Reference);
                //if (nbrefiche >= 1)
                //{

                //    return View(model);
                //}

                BusinessGestionSortie.Instance.Ajouter(dto);


                return RedirectToAction("Index");
            }
            else
            {
                model.Date = DateTime.Now;
                return View(model);
            }

        }



        [HttpGet]
        public ActionResult Modifier(int id)
        {

            ModelModifierSortie model = new ModelModifierSortie();

            model.ListeFiches = BusinessGestionSortie.Instance.GetListeTypeSortie();

            SortieDto dto = BusinessGestionSortie.Instance.GetSortieParId(id);

            if (dto != null)
            {
                model.id = dto.id;
                model.Reference = dto.Reference;
                model.ReferenceTypeSortie = dto.ReferenceTypeSortie;
                model.NumeroFacture = dto.NumeroFacture;
                model.Client = dto.Client;
                model.Employe = dto.Employe;
                model.Date = dto.Date;
                model.idTypeSortie = dto.idTypeSortie;
                model.TypeSortie = dto.TypeSortie;
                model.B12 = dto.B12;
                model.B9 = dto.B9;
                model.B6R = dto.B6R;
                model.B6V = dto.B6V;
                model.B3 = dto.B3;
                model.B35 = dto.B35;
                model.Presentoir = dto.Presentoir;

                

                model.Commentaire = dto.Commentaires;
                model.etat = dto.etat;


            };


            return View(model);
        }




        [HttpPost]
        public ActionResult Modifier(ModelModifierSortie model)
        {



            if (ModelState.IsValid)
            {

                SortieDto dto = new SortieDto
                {
                    id = model.id,
                    Reference = model.Reference,
                    ReferenceTypeSortie = model.ReferenceTypeSortie,
                    NumeroFacture = model.NumeroFacture,

GUHabitat-Old/Views/Sortie/Acloturer.cshtml
@using PagedList.Mvc

@model GUHabitat.Models.ModelListeSortie
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@if (TempData["SuccessMessage"] != null)
{
    <span style="color:green;">@TempData["SuccessMessage"] </span>
}
@if (TempData["ErrorMessage"] != null)
{
    <span style="color:red;">@TempData["ErrorMessage"] </span>
}



@if (!Model.ListeSortie.Any())
{
    <div class="alert alert-danger">
        Pas d'instance
    </div>

}
else
{

    <h4> <span class="badge badge-success">Nombre Instance :  @ViewBag.nbInstance</span></h4>
    <br /><br />

    <div>
        <form class="form-inline" action="~/Sortie/Acloturer">
            <div class="magin"></div>
            <div class="form-group left ">

                @Html.TextBoxFor(x => x.filtreMotCle, new { @class = "form-control left", @type = "date" })&ensp;

                @*@Html.TextBoxFor(x => x.filtreMotCle, new { @class = "form-control left", @autocomplete = "off", @placeholder = "Mot Clé" })&ensp;*@

            </div>
            <div class="form-group right ">
                <button type="submit" class="btn btn-primary right" id="buttonChercher">Chercher</button>
            </div>

        </form>


        <br />
        <div id="divAjaxContainer">

            @*<input id="checkall" type="checkbox"> Tout
                <br />
                <br />*@

            <div class="table-responsive">

                <table class="table table-bordered table-hover" name="frm">
                    <thead class="section-colored alert-success">
                        <tr>
                            @*<th>Cocher</th>*@
                            <th class="text-lg-center">Date</th>
                            <th class="text-lg-center">Type Sortie</th>
                            <th class="text-lg-center">Référence</th>
                            <th class="text-lg-center">Concerné</th>
                            <th class="text-lg-center">B12</th>
                            <th class="text-lg-center">B09</th>
                            <th class="text-lg-center">B6R</th>
                            <th class="text-lg-center">B6V</th>
                            <th class="text-lg-center">B03</th>
                            <th class="text-lg-center">B35</th>
                            <th class="text-lg-center">Etat</th>
                            <th class="text-lg-center">Actions</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ListeSortie)
                        {
                            <tr>
                                @*<td><input type="checkbox" name="chk_1" class="deleteCheckbox" pkey="@item.id" value=""></td>*@
                                <td class="text-lg-center">@item.Date.ToShortDateString()</td>
                                <td class="text-lg-center">@item.TypeSortie </td>
                                <td class="text-lg-center">@item.ReferenceTypeSortie </td>
                                @if (item.idTypeSortie != 2)
                                {
                                    <td class="text-lg-center">@item.Client </td>
                                }
                                @if (item.idTypeSortie == 2)
                                {
                                    <td class="text-lg-center">@item.Employe </td>
                                }
                                <td class="text-lg-center">@item.B12</td>
                                <td class="text-lg-center">@item.B9</td>
                                <td class="text-lg-center">@item.B6R</td>
                                <td class="text-lg-center">@item.B6V</td>
                                <td class="text-lg-center">@item.B3 </td>
                                <td class="text-lg-center">@item.B35 </td>

                                <td class="text-lg-center">@item.etatString </td>

                                <td class="text-lg-center">
                                    <a href="@Url.Action("Details","Sortie", new { id = item.id})" class="btn btn-outline-info">
                                        <i class="fas fa-fw fa-info-circle"></i>
                                        Details
                                    </a>

                                </td>


                            </tr>
                        }

                    </tbody>

                </table>

            </div>




            <div class="pager">
                Page @(Model.ListeSortie.PageCount < Model.ListeSortie.PageNumber ? 0 : Model.ListeSortie.PageNumber)
                / @Model.ListeSortie.PageCount   @Html.PagedListPager(Model.ListeSortie, page => Url.Action("Acloturer", new { page, filtreMotCle = Model.filtreMotCle }))
            </div>
        </div>

        <hr />

        <div class="text-center">

            @*@if (User.IsInRole("Admin"))
            {


                <button type="submit" class="btn btn-outline-primary" id="btnPrintSelected">Clôturer</button>

            }*@


            @if (User.IsInRole("Admin"))
            {
            <a class="btn btn-outline-primary" href="#" data-toggle="modal" data-target="#CloturerParDate">
                <i class="fas fa-fw fa-lock"></i>
                Clôturer
            </a>

            }


        </div>



    </div>

}


<div class="modal fade" id="CloturerParDate" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Etês vous sûre de vouloir Clôturer les enregistrement liés à cette date : @Model.filtreMotCle</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>

                <a href="@Url.Action("CloturerParDate","Sortie", new { date =  Model.filtreMotCle})" class="btn btn-primary">

                    Clôturer
                </a>
            </div>
        </div>
    </div>
</div>


<script>

 $(document).on('click', '#btnPrintSelected', function (event) {
        var idArray = new Array();

        $("input:checked.deleteCheckbox").each(function (i) {
            idArray[i] = $(this).attr('pkey');
        });

       var ROOT = '@Url.Content("~/")';

     $.ajax({
         type: "POST",
         url: ROOT + "/Sortie/Selected",
         dataType: "json",
         traditional: true,
         data: {
             ids: idArray
         }


     })

            .done(function () {
                alert("success");
            })
            .fail(function () {


                $("#frmPrint").submit();
            })
        //
     event.preventDefault();
     window.location.href = ROOT + '/Sortie/Index';

  });




    $("#checkall").change(function () {
        $(".deleteCheckbox").prop("checked", $(this).prop("checked"))
    })


</script>

GUHabitat-Old/Views/Sortie/Index.cshtml
@using PagedList.Mvc
@{
    ViewBag.Title = "Liste des Sorties";
}
@model GUHabitat.Models.ModelListeSortie
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@if (TempData["SuccessMessage"] != null)
{
    <span style="color:green;">@TempData["SuccessMessage"] </span>
}
@if (TempData["ErrorMessage"] != null)
{
    <span style="color:red;">@TempData["ErrorMessage"] </span>
}
<br />
<br />
<div>
    <form class="form-inline" action="~/Sortie/Index">
        <div class="magin"></div>
        <div class="form-group left ">

            @Html.TextBoxFor(x => x.filtreMotCle, new { @class = "form-control left", @autocomplete = "off", @placeholder = "Mot Clé" })&ensp;

        </div>
        <div class="form-group right ">
            <button type="submit" class="btn btn-primary right" id="buttonChercher">Chercher</button>
        </div>
    </form>
    <br />
    <div id="divAjaxContainer">
        <div class="table-responsive">

            <table class="table table-bordered table-hover">
                <thead class="section-colored alert-success">
                    <tr>
                        @*<th class="text-lg-center">Référence</th>*@
                        <th class="text-lg-center">Date</th>
                        <th class="text-lg-center">Type Sortie</th>
                        <th class="text-lg-center">Référence Type</th>
                        <th class="text-lg-center">Concerné</th>
                        <th class="text-lg-center">B12</th>
                        <th class="text-lg-center">B09</th>
                        <th class="text-lg-center">B6R</th>
                        <th class="text-lg-center">B6V</th>
                        <th class="text-lg-center">B03</th>
                        <th class="text-lg-center">B35</th>
                        <th class="text-lg-center">Etat</th>
                        <th class="text-lg-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ListeSortie)
                    {
                    <tr>
                        @*<td class="text-lg-center">@item.Reference</td>*@
                        <td class="text-lg-center">@item.Date.ToShortDateString()</td>
                        <td class="text-lg-center">@item.TypeSortie </td>
                        <td class="text-lg-center">@item.ReferenceTypeSortie </td>

                        @if (item.idTypeSortie != 2)
                        {
                            <td class="text-lg-center">@item.Client </td>
                        }
                        @if (item.idTypeSortie == 2)
                        {
                            <td class="text-lg-center">@item.Employe </td>
                        }
                        <td class="text-lg-center">@item.B12</td>
                        <td class="text-lg-center">@item.B9</td>
                        <td class="text-lg-center">@item.B6R</td>
                        <td class="text-lg-center">@item.B6V</td>
                        <td class="text-lg-center">@item.B3 </td>
                        <td class="text-lg-center">@item.B35 </td>

                        <td class="text-lg-center">@item.etatString </td>


                        <td class="text-lg-center">
                            <a href="@Url.Action("Details","Sortie", new { id = item.id})" class="btn btn-outline-info">
                                <i class="fas fa-fw fa-info-circle"></i>
                                Details
                            </a>

                        </td>



                    </tr>
                    }

                </tbody>

            </table>

        </div>




        <div class="pager">
            Page @(Model.ListeSortie.PageCount < Model.ListeSortie.PageNumber ? 0 : Model.ListeSortie.PageNumber)
            / @Model.ListeSortie.PageCount   @Html.PagedListPager(Model.ListeSortie, page => Url.Action("Index", new { page, filtreMotCle = Model.filtreMotCle }))
        </div>
    </div>

</div>





@*<script>
        $(document).ready(function () {
            toastr.success("Test");
        });
    </script>*@

GUHabitat-Old/Views/Sortie/Valider.cshtml
@using PagedList.Mvc

@model GUHabitat.Models.ModelListeSortie
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@if (TempData["SuccessMessage"] != null)
{
    <span style="color:green;">@TempData["SuccessMessage"] </span>
}
@if (TempData["ErrorMessage"] != null)
{
    <span style="color:red;">@TempData["ErrorMessage"] </span>
}



@if (!Model.ListeSortie.Any())
{
    <div class="alert alert-danger">
        Pas d'instance
    </div>

}
else
{

    <h4> <span class="badge badge-success">Nombre Instance :  @ViewBag.nbInstance</span></h4>
    <br />

    <div>
        <form class="form-inline" action="~/Sortie/Valider">
            <div class="magin"></div>
            <div class="form-group left ">

                @*@Html.TextBoxFor(x => x.filtreMotCle, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker", @type = "date" })*@
                @Html.TextBoxFor(x => x.filtreMotCle, new { @class = "form-control left", @type = "date" })&ensp;
            </div>
            <div class="form-group right ">
                <button type="submit" class="btn btn-primary right" id="buttonChercher">Chercher</button>
            </div>

        </form>


        <br />
        <div id="divAjaxContainer">

            @*<input id="checkall" type="checkbox"> Tout
            <br />
            <br />*@
            <br />
            <div class="table-responsive">

                <table class="table table-bordered table-hover" name="frm">
                    <thead class="section-colored alert-success">
                        <tr>
                            @*<th>Cocher</th>*@
                            <th class="text-lg-center">Date</th>
                            <th class="text-lg-center">Type Sortie</th>
                            <th class="text-lg-center">Référence</th>
                            <th class="text-lg-center">Concerné</th>
                            <th class="text-lg-center">B12</th>
                            <th class="text-lg-center">B09</th>
                            <th class="text-lg-center">B6R</th>
                            <th class="text-lg-center">B6V</th>
                            <th class="text-lg-center">B03</th>
                            <th class="text-lg-center">B35</th>
                            <th class="text-lg-center">Etat</th>
                            <th class="text-lg-center">Actions</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ListeSortie)
                        {
                            <tr>
                                @*<td><input type="checkbox" name="chk_1" class="deleteCheckbox" pkey="@item.id" value=""></td>*@
                                <td class="text-lg-center">@item.Date.ToShortDateString()</td>
                                <td class="text-lg-center">@item.TypeSortie </td>
                                <td class="text-lg-center">@item.ReferenceTypeSortie </td>
                                @if (item.idTypeSortie != 2)
                                {
                                    <td class="text-lg-center">@item.Client </td>
                                }
                                @if (item.idTypeSortie == 2)
                                {
                                    <td class="text-lg-center">@item.Employe </td>
                                }
                                <td class="text-lg-center">@item.B12</td>
                                <td class="text-lg-center">@item.B9</td>
                                <td class="text-lg-center">@item.B6R</td>
                                <td class="text-lg-center">@item.B6V</td>
                                <td class="text-lg-center">@item.B3 </td>
                                <td class="text-lg-center">@item.B35 </td>

                                <td class="text-lg-center">@item.etatString </td>

                                <td class="text-lg-center">
                                    <a href="@Url.Action("Details","Sortie", new { id = item.id})" class="btn btn-outline-info">
                                        <i class="fas fa-fw fa-info-circle"></i>
                                        Details
                                    </a>

                                </td>


                            </tr>
                        }

                    </tbody>

                </table>

            </div>




            <div class="pager">
                Page @(Model.ListeSortie.PageCount < Model.ListeSortie.PageNumber ? 0 : Model.ListeSortie.PageNumber)
                / @Model.ListeSortie.PageCount   @Html.PagedListPager(Model.ListeSortie, page => Url.Action("Valider", new { page, filtreMotCle = Model.filtreMotCle }))
            </div>
        </div>

        <hr />

        <div class="text-center">

            @if (User.IsInRole("ServiceDC"))
            {
                <a class="btn btn-outline-primary" href="#" data-toggle="modal" data-target="#ValiderParDate">
                    <i class="fas fa-fw fa-check"></i>
                    Valider
                </a>

            }

           @*@if (User.IsInRole("ServiceDC"))
            {

                <button type="submit" class="btn btn-outline-primary" id="btnPrintSelected">Valider</button>

            }*@




        </div>

       


    </div>

}



    <div class="modal fade" id="ValiderParDate" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Etês vous sûre de vouloir Valider les enregistrement liés à cette date : @Model.filtreMotCle</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>

                    <a href="@Url.Action("ValiderParDate","Sortie", new { date =  Model.filtreMotCle})" class="btn btn-primary">

                        Valider
                    </a>
                </div>
            </div>
        </div>
    </div>

<script>

    $(function () {
        $(".datepicker").datepicker({
            dateFormat: 'dd-mm-yy',
            separator: '-',
        });
    });




 $(document).on('click', '#btnPrintSelected', function (event) {
        var idArray = new Array();

        $("input:checked.deleteCheckbox").each(function (i) {
            idArray[i] = $(this).attr('pkey');
        });

       var ROOT = '@Url.Content("~/")';

     $.ajax({
         type: "POST",
         url: ROOT + "/Sortie/SelectedValider",
         dataType: "json",
         traditional: true,
         data: {
             ids: idArray
         }


     })

            .done(function () {
                alert("success");
            })
            .fail(function () {


                $("#frmPrint").submit();
            })
        //
     event.preventDefault();
     window.location.href = ROOT + '/Sortie/Index';

  });




    $("#checkall").change(function () {
        $(".deleteCheckbox").prop("checked", $(this).prop("checked"))
    })


</script>