GUHabitat-Old/Controllers/StockCentreController.cs
using GUHabitat.BLL;
using GUHabitat.DTO;
using GUHabitat.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace GUHabitat.Controllers
{
    public class StockCentreController : Controller
    {
       
        [HttpPost]
        public ActionResult ValiderStockCentre(int CodeCentreStock)
        {
            return RedirectToAction("Ajouter", new { CodeCentreStock = CodeCentreStock });
        }



        // GET: StockCentre
        public ActionResult Index(string filtreMotCle, int? page)
        {

            ModelListeStockCentre model = new ModelListeStockCentre();
            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);
            model.filtreMotCle = filtreMotCle;
            int pageSize = 10;
            int pageIndex = page.HasValue ? page.Value : 1;
            model.ListeStockCentre = BusinessGestionStockCentre.Instance.ChercherListeStockCentre(model.filtreMotCle, idEntite, login).ToPagedList(pageIndex, pageSize);

            return View(model);
        }



        [HttpGet]
        public ActionResult Details(int id)
        {

            ModelAjouterStockCentre model = new ModelAjouterStockCentre();


            StockCentreDto dto = BusinessGestionStockCentre.Instance.GetStockCentreParId(id);

            if (dto != null)
            {
                model.id = dto.id;
                model.reference = dto.reference;
                model.Date = dto.Date;
                model.CodeCentre = dto.CodeCentre;
                model.LibelleCentre = dto.LibelleCentre;

                model.StockTheorie = dto.StockTheorie;
                model.Stock = dto.Stock;
                model.StockFin = dto.StockFin;
                model.Depotage = dto.Depotage;
                model.GainPerte = dto.GainPerte;
                model.Commentaire = dto.Commentaire;

                model.etat = dto.etat;



            };
            return View(model);

        }



        public ActionResult EnInstance(int id)
        {


            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            GetUser.GetUserr(login);

            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);

            BusinessGestionStockCentre.Instance.EnInstance(idEntite, id);

            return RedirectToAction("Index");
        }



        public ActionResult Valider(int id)
        {

            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            GetUser.GetUserr(login);

            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);

            BusinessGestionStockCentre.Instance.Valider(idEntite, id);


            return RedirectToAction("Index");
        }




        [HttpGet]
        public ActionResult Ajouter(int CodeCentreStock)
        {

            ModelAjouterStockCentre model = new ModelAjouterStockCentre();
            model.Date = DateTime.Now;

            model.reference = Convert.ToInt32(GetNewCode());

            model.CodeCentre = BusinessGestionStockCentre.Instance.GetCentreParCode(CodeCentreStock).Code;

            model.Stock = Convert.ToDecimal(BusinessGestionStockCentre.Instance.StockDeut(model.CodeCentre).ToString("0.000"));
        


            return View(model);
        }




        [HttpPost]
        public ActionResult Ajouter(ModelAjouterStockCentre model)
        {


            if (ModelState.IsValid)
            {

                if (model.CodeCentre == 9)
                {
                    model.StockTheorie = Convert.ToDecimal(BusinessGestionStockCentre.Instance.StockAujourdhui(model.CodeCentre,model.Date).ToString("0.000"));
                }
                if (model.CodeCentre != 9 && model.CodeCentre != 0)
                {
                    model.StockTheorie = Convert.ToDecimal(BusinessGestionStockCentre.Instance.StockAujourdhuiInterieur(model.CodeCentre,model.Date).ToString("0.000"));
                }



                StockCentreDto dto = new StockCentreDto
                {
                    idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value),

                    reference = model.reference,
                    Date = model.Date,
                    CodeCentre = model.CodeCentre,
                   
                    Stock = model.Stock,
                    StockFin = model.StockFin,
                    StockTheorie = model.StockTheorie,
                    Depotage = model.Depotage,
                    GainPerte = model.StockFin >= 0 ? (model.StockFin - model.StockTheorie) : 0,
                    Commentaire = model.Commentaire,

                    etat = model.etat

                };


                string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
                GetUser.GetUserr(login);

               


               
                var nbre = BusinessGestionStockCentre.Instance.GetStockParDate(model.CodeCentre,model.Date);
                if (nbre > 0)
                {
                    ViewBag.MessageAjouter = "Cette date  deja saisie";

                    return View(model);
                }

               

                BusinessGestionStockCentre.Instance.Ajouter(dto);





                return RedirectToAction("Index");
            }
            else
            {
                model.Date = DateTime.Now;
                return View(model);
            }

        }




        public void AjoutGainPerte(int CodeCentre , DateTime date,decimal StockTheorie,decimal Stock)
        {


            using (var _context = new GUHabitat.DAL.GUHabitatDBEntities())
            {
               
                var DateStockHier = _context.StockCentres.Where(x => x.CodeCentre == CodeCentre).OrderByDescending(r => r.Date).Select(x => x.Date).FirstOrDefault();
                var entity = _context.StockCentres.Where(x => x.CodeCentre == CodeCentre && x.Date == DateStockHier).SingleOrDefault();

                entity.GainPerte = StockTheorie > 0 ? (Stock - StockTheorie) : 0;

                _context.Entry(entity).State = EntityState.Modified;
                _context.SaveChanges();

            }

        }






        [HttpGet]
        public ActionResult Modifier(int id)
        {

            ModelModiferStockCentre model = new ModelModiferStockCentre();
            model.ListeCentre = BusinessGestionStockCentre.Instance.GetListeCentre();


             StockCentreDto dto = BusinessGestionStockCentre.Instance.GetStockCentreParId(id);

            if (dto != null)
            {
                model.id = dto.id;
                model.reference = dto.reference;
                model.Date = dto.Date;
                model.CodeCentre = dto.CodeCentre;
                model.LibelleCentre = dto.LibelleCentre;
                //model.StockTheorie = Convert.ToDecimal(dto.StockTheorie.ToString("0.000"));
                model.Stock = Convert.ToDecimal(BusinessGestionStockCentre.Instance.StockDeut(model.CodeCentre,model.Date).ToString("0.000")) > 0 ? Convert.ToDecimal(BusinessGestionStockCentre.Instance.StockDeut(model.CodeCentre, model.Date).ToString("0.000")) : dto.Stock;
                model.StockFin = dto.StockFin;
                model.Depotage = dto.Depotage;
               

                model.Commentaire = dto.Commentaire;

                model.etat = dto.etat;


            };

             //model.Stock = Convert.ToDecimal(BusinessGestionStockCentre.Instance.StockDeut(model.CodeCentre,model.Date).ToString("0.000"));

            if (model.CodeCentre == 9)
            {
                model.StockTheorie = Convert.ToDecimal(BusinessGestionStockCentre.Instance.StockAujourdhui(model.CodeCentre, model.Date).ToString("0.000"));
            }
            if (model.CodeCentre != 9 && model.CodeCentre != 0)
            {
                model.StockTheorie = Convert.ToDecimal(BusinessGestionStockCentre.Instance.StockAujourdhuiInterieur(model.CodeCentre,model.Date).ToString("0.000"));
            }

            return View(model);


        }




        [HttpPost]
        public ActionResult Modifier(ModelModiferStockCentre model)
        {


            if (ModelState.IsValid)
            {

               


                StockCentreDto dto = new StockCentreDto
                {

                    idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value),
                    id = model.id,
                    reference = model.reference,
                    Date = model.Date,
                    CodeCentre = model.CodeCentre,
                    LibelleCentre = model.LibelleCentre,
                    
                    Stock = model.Stock,
                    StockFin = model.StockFin,
                    StockTheorie = model.StockTheorie,
                    Depotage = model.Depotage,
                    GainPerte = model.StockFin >= 0 ? (model.StockFin - model.StockTheorie) : 0,
                    Commentaire = model.Commentaire,

                    etat = model.etat

                };


                string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
                GetUser.GetUserr(login);




              

                //ModifierGainPerte(model.CodeCentre, model.Date, model.StockTheorie, model.Stock);
                BusinessGestionStockCentre.Instance.Modifier(dto);




                

                return RedirectToAction("Index");
            }
            else
            {

GUHabitat-Old/Views/StockCentre/Ajouter.cshtml
@model GUHabitat.Models.ModelAjouterStockCentre
@{
    ViewBag.Title = "";
}

<h4> <span class="badge badge-success">Centre : @Model.libelleCentreString</span></h4>

<hr />

@if (ViewBag.MessageAjouter != null)
{
    <div class="alert alert-danger">
        @ViewBag.MessageAjouter

    </div>

}

<form action="~/StockCentre/Ajouter" method="post" id="form" class="form-horizontal">
    @Html.HiddenFor(x => x.id)
    @Html.HiddenFor(x => x.CodeCentre)

    <!-- Tab panes -->
    <div class="tab-content">

        <br />

        <div class="row col-12">

            <div class="row col-12">
                <h4>
                    <span class="badge badge-success">Informations Génerale</span>
                </h4>
            </div>

            <br /><br />

            <div class="row">

                <div class="form-group col-sm-4 ">
                    <label for="NniM">Reference</label>
                    @Html.TextBoxFor(x => x.reference, new { @class = "form-control", @readonly = "true", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.reference)
                </div>

                <div class="form-group col-sm-5 ">
                    <label for="Date"> Date </label>
                    @Html.TextBoxFor(x => x.Date, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker" })
                    @Html.ValidationMessageFor(x => x.Date)
                </div>


            </div>


        </div>


        <hr />
        <div class="row col-12">

            <div class="row col-12">
                <h4>
                    <span class="badge badge-success"> Stock</span>
                </h4>


            </div>


            <br /><br />


                  <div class="row col-12">

                      @*<div class="form-group col-sm-2">
                          <label>Stock Théorie</label>
                          @Html.TextBoxFor(x => x.StockTheorie, new { @class = "form-control", @autocomplete = "off", @readonly = "true" })
                          @Html.ValidationMessageFor(x => x.StockTheorie)
                      </div>*@

                      <div class="form-group col-sm-2">
                          <label>Stock Debut</label>
                          @Html.TextBoxFor(x => x.Stock, new { @class = "form-control", @autocomplete = "off" })
                          @Html.ValidationMessageFor(x => x.Stock)
                      </div>

                      <div class="form-group col-sm-2">
                          <label>Stock Fin</label>
                          @Html.TextBoxFor(x => x.StockFin , new { @class = "form-control", @autocomplete = "off" })
                          @Html.ValidationMessageFor(x => x.StockFin)
                      </div>

                      @if (Model.CodeCentre == 9)
                      {
                          <div class="form-group col-sm-2">
                              <label>Dépotage</label>
                              @Html.TextBoxFor(x => x.Depotage, new { @class = "form-control", @autocomplete = "off" })
                              @Html.ValidationMessageFor(x => x.Depotage)
                          </div>

                      }

                  </div>





        </div>

        <hr />

        <div class="row">
            <div class="form-group col-sm-12">
                <label for="nomFamilleM">Commentaires</label>
                @Html.TextAreaFor(x => x.Commentaire, new { @class = "form-control", @autocomplete = "off" })
                @Html.ValidationMessageFor(x => x.Commentaire)
            </div>

        </div>


        <hr />



        <br /><br />

        @if (User.IsInRole("ServiceDC") || User.IsInRole("ServiceDE"))
        {
            <div class="text-center">
                <button type="submit" class="btn btn-outline-primary ">Enregistrer</button>
            </div>
        }

    </div>
</form>
<script>
    $(function () {
        $(".datepicker").datepicker({
            dateFormat: 'dd-mm-yy',
            separator: '-',
        });
    });

    $(function () {
        $('#datetimepicker3').datetimepicker({
            dateFormat: 'HH:mm'
        });
    });





    $('form').submit(function () {
        $(this).find(':submit').attr('disabled', 'disabled');
    });





</script>

GUHabitat-Old/Views/StockCentre/Details.cshtml
@model GUHabitat.Models.ModelAjouterStockCentre
@{
    ViewBag.Title = "";
}

<h4> <span class="badge badge-success">Centre : @Model.LibelleCentre</span></h4>

<hr />



@if ((User.IsInRole("ServiceDC") || User.IsInRole("ServiceDE")) && (Model.etat != 2 && Model.etat != 3))
{
    <a href="@Url.Action("Modifier", "StockCentre", new { id = Model.id })" class="btn btn-outline-primary">
        <i class="fas fa-fw fa-edit"></i>
        Modifier
    </a>
}


@if ((User.IsInRole("ServiceDC") || User.IsInRole("ServiceDE")) && (Model.etat == 2))
{
    <a class="btn btn-outline-primary" href="#" data-toggle="modal" data-target="#InstanceStockCentre">
        <i class="fas fa-fw fa-arrow-alt-circle-left"></i>
        En Instance
    </a>

}

@if ((User.IsInRole("ServiceDC") || User.IsInRole("ServiceDE")) && (Model.etat == 1))
{
    <a class="btn btn-outline-primary" href="#" data-toggle="modal" data-target="#Valider">
        <i class="fas fa-check"></i>
        Valider
    </a>

}


<form action="~/StockCentre/Ajouter" method="post" id="form" class="form-horizontal">
    @Html.HiddenFor(x => x.id)
    @Html.HiddenFor(x => x.CodeCentre)

    <!-- Tab panes -->
    <div class="tab-content">

        <br />

        <div class="row col-12">

            <div class="row col-12">
                <h4>
                    <span class="badge badge-success">Informations Génerale</span>
                </h4>
            </div>

            <br /><br />

            <div class="row">

                <div class="form-group col-sm-4 ">
                    <label for="NniM">Reference</label>
                    @Html.TextBoxFor(x => x.reference, new { @class = "form-control", @readonly = "true", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.reference)
                </div>

                <div class="form-group col-sm-5 ">
                    <label for="Date"> Date </label>
                    @Html.TextBoxFor(x => x.Date, "{0:dd/MM/yyyy}", new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.Date)
                </div>


            </div>


        </div>


        <hr />
        <div class="row col-12">

            <div class="row col-12">
                <h4>
                    <span class="badge badge-success">Stock</span>
                </h4>


            </div>


            <br /><br />


                  <div class="row col-12">





                      <div class="form-group col-sm-2">
                          <label>Stock Debut</label>
                          @Html.TextBoxFor(x => x.Stock, new { @class = "form-control", @autocomplete = "off", @readonly = "true" })
                          @Html.ValidationMessageFor(x => x.Stock)
                      </div>
                      <div class="form-group col-sm-2">
                          <label>Stock Théorie</label>
                          @Html.TextBoxFor(x => x.StockTheorie, new { @class = "form-control", @autocomplete = "off", @readonly = "true" })
                          @Html.ValidationMessageFor(x => x.StockTheorie)
                      </div>
                      <div class="form-group col-sm-2">
                          <label>Stock Fin</label>
                          @Html.TextBoxFor(x => x.StockFin, new { @class = "form-control", @autocomplete = "off", @readonly = "true" })
                          @Html.ValidationMessageFor(x => x.StockFin)
                      </div>

                      @if (Model.CodeCentre == 9)
                      {
                          <div class="form-group col-sm-2">
                              <label>Dépotage</label>
                              @Html.TextBoxFor(x => x.Depotage, new { @class = "form-control", @autocomplete = "off", @readonly = "true" })
                              @Html.ValidationMessageFor(x => x.Depotage)
                          </div>

                      }

                      <div class="form-group col-sm-2">
                          <label>Gain / Perte</label>
                          @Html.TextBoxFor(x => x.GainPerte, new { @class = "form-control", @autocomplete = "off", @readonly = "true" })
                          @Html.ValidationMessageFor(x => x.GainPerte)
                      </div>
                  </div>

        </div>



        <hr />


        <div class="row">
            <div class="form-group col-sm-12">
                <label for="nomFamilleM">Commentaires</label>
                @Html.TextAreaFor(x => x.Commentaire, new { @class = "form-control", @autocomplete = "off", @readonly = "true" })
                @Html.ValidationMessageFor(x => x.Commentaire)
            </div>

        </div>


        <hr />



        <br /><br />

    </div>
</form>


<!-- EnInstance Modal-->
<div class="modal fade" id="InstanceStockCentre" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Etês vous sûre de vouloir mettre En Instance cet document?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>

                <a href="@Url.Action("EnInstance","StockCentre", new { id = Model.id})" class="btn btn-primary">
                    En Instance
                </a>
            </div>
        </div>
    </div>
</div>


<!-- Valider Modal-->
<div class="modal fade" id="Valider" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Etês vous sûre de vouloir Valider cet document?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>

                <a href="@Url.Action("Valider","StockCentre", new { id = Model.id})" class="btn btn-primary">
                    Valider
                </a>
            </div>
        </div>
    </div>
</div>



<script>
    $(function () {
        $(".datepicker").datepicker({
            dateFormat: 'dd-mm-yy',
            separator: '-',
        });
    });

    $(function () {
        $('#datetimepicker3').datetimepicker({
            dateFormat: 'HH:mm'
        });
    });





    $('form').submit(function () {
        $(this).find(':submit').attr('disabled', 'disabled');
    });





</script>

GUHabitat-Old/Views/StockCentre/Index.cshtml
@using PagedList.Mvc
@{
    ViewBag.Title = "Liste Stock Centre";
}
@model GUHabitat.Models.ModelListeStockCentre
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@if (TempData["SuccessMessage"] != null)
{
    <span style="color:green;">@TempData["SuccessMessage"] </span>
}
@if (TempData["ErrorMessage"] != null)
{
    <span style="color:red;">@TempData["ErrorMessage"] </span>
}
<br />
<br />
<div>
    <form class="form-inline" action="~/StockCentre/Index">
        <div class="magin"></div>
        <div class="form-group left ">

            @Html.TextBoxFor(x => x.filtreMotCle, new { @class = "form-control datepicker left", @autocomplete = "off", @placeholder = "Date" })&ensp;

        </div>
        <div class="form-group right ">
            <button type="submit" class="btn btn-primary right" id="buttonChercher">Chercher</button>
        </div>
    </form>
    <br />
    <div id="divAjaxContainer">
        <div class="table-responsive">

            <table class="table table-bordered table-hover">
                <thead class="section-colored alert-success">
                    <tr>
                        <th class="text-lg-center">Date</th>
                        <th class="text-lg-center">Centre</th>
                        <th class="text-lg-center">Stock Début</th>
                        <th class="text-lg-center">Stock Fin</th>

                        <th class="text-lg-center">Etat</th>
                        <th class="text-lg-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ListeStockCentre)
                    {
                        <tr>
                           
                            <td class="text-lg-center">@item.Date.ToShortDateString()</td>
                            <td class="text-lg-center">@item.LibelleCentre </td>
                            <td class="text-lg-center">@item.Stock</td>
                            <td class="text-lg-center">@item.StockFin</td>

                            <td class="text-lg-center">@item.etatString </td>

                            <td class="text-lg-center">
                                <a href="@Url.Action("Details","StockCentre", new { id = item.id})" class="btn btn-outline-info">
                                    <i class="fas fa-fw fa-info-circle"></i>
                                    Details
                                </a>

                            </td>



                        </tr>
                    }

                </tbody>

            </table>

        </div>




        <div class="pager">
            Page @(Model.ListeStockCentre.PageCount < Model.ListeStockCentre.PageNumber ? 0 : Model.ListeStockCentre.PageNumber)
            / @Model.ListeStockCentre.PageCount   @Html.PagedListPager(Model.ListeStockCentre, page => Url.Action("Index", new { page, filtreMotCle = Model.filtreMotCle }))
        </div>
    </div>

</div>

<script>
    $(function () {
        $(".datepicker").datepicker({
            dateFormat: 'dd-mm-yy',
            separator: '-',
        });
    });

</script>




@*<script>
        $(document).ready(function () {
            toastr.success("Test");
        });
    </script>*@

GUHabitat-Old/Views/StockCentre/Modifier.cshtml
@model GUHabitat.Models.ModelModiferStockCentre
@{
    ViewBag.Title = "";
}

<h4> <span class="badge badge-success">Centre : @Model.LibelleCentre</span></h4>

<hr />


@if (ViewBag.MessageModifier != null)
{
    <div class="alert alert-danger">
        @ViewBag.MessageModifier

    </div>
}
    
    <form action="~/StockCentre/Modifier" method="post" id="form" class="form-horizontal">
        @Html.HiddenFor(x => x.id)

        <!-- Tab panes -->
        <div class="tab-content">

            <br />

            <div class="row col-12">

                <div class="row col-12">
                    <h4>
                        <span class="badge badge-success">Informations Génerale</span>
                    </h4>
                </div>

                <br /><br />

                <div class="row">

                    <div class="form-group col-sm-4 ">
                        <label for="NniM">Reference</label>
                        @Html.TextBoxFor(x => x.reference, new { @class = "form-control", @readonly = "true", @autocomplete = "off" })
                        @Html.ValidationMessageFor(x => x.reference)
                    </div>

                    <div class="form-group col-sm-4 ">
                        <label for="Date"> Date </label>
                        @Html.TextBoxFor(x => x.Date, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker " })
                        @Html.ValidationMessageFor(x => x.Date)
                    </div>

                    <div class="form-group col-sm-4 ">
                        <label for="Entite">Centre</label>
                        @Html.DropDownListFor(x => x.CodeCentre, new SelectList(Model.ListeCentre, "Code", "libelle"), "--Choix Centre --", new { @class = "form-control", @id = "Centre" })
                        @Html.ValidationMessageFor(x => x.CodeCentre)
                    </div>

                </div>


            </div>


            <hr />
            <div class="row col-12">

                <div class="row col-12">
                    <h4>
                        <span class="badge badge-success">Stock</span>
                    </h4>


                </div>

                <br /><br />


                      <div class="row col-12">



                          <div class="form-group col-sm-2">
                              <label>Stock Debut</label>
                              @Html.TextBoxFor(x => x.Stock, new { @class = "form-control", @autocomplete = "off" })
                              @Html.ValidationMessageFor(x => x.Stock)
                          </div>

                          <div class="form-group col-sm-2">
                            <label>Stock Théorie</label>
                                @Html.TextBoxFor(x => x.StockTheorie, new { @class = "form-control", @autocomplete = "off", @readonly = "true" })
                                @Html.ValidationMessageFor(x => x.StockTheorie)
                          </div>

                          <div class="form-group col-sm-2">
                              <label>Stock Fin</label>
                              @Html.TextBoxFor(x => x.StockFin, new { @class = "form-control", @autocomplete = "off" })
                              @Html.ValidationMessageFor(x => x.StockFin)
                          </div>
                          @if (Model.CodeCentre == 9)
                          {
                              <div class="form-group col-sm-2">
                                  <label>Dépotage</label>
                                  @Html.TextBoxFor(x => x.Depotage, new { @class = "form-control", @autocomplete = "off" })
                                  @Html.ValidationMessageFor(x => x.Depotage)
                              </div>

                          }

                      </div>

            </div>



            <hr />

            <div class="row">
                <div class="form-group col-sm-12">
                    <label for="nomFamilleM">Commentaires</label>
                    @Html.TextAreaFor(x => x.Commentaire, new { @class = "form-control", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.Commentaire)
                </div>

            </div>


            <hr />



            <br /><br />

            @if (User.IsInRole("ServiceDC") || User.IsInRole("ServiceDE"))
            {
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-primary ">Enregistrer</button>
                </div>
            }

        </div>
    </form>
    <script>
    $(function () {
        $(".datepicker").datepicker({
            dateFormat: 'dd-mm-yy',
            separator: '-',
        });
    });

    $(function () {
        $('#datetimepicker3').datetimepicker({
            dateFormat: 'HH:mm'
        });
    });





    $('form').submit(function () {
        $(this).find(':submit').attr('disabled', 'disabled');
    });


    document.getElementById("Centre").value  = @Model.CodeCentre;


    </script>