GUHabitat-Old/Controllers/DotationCentreController.cs
using GUHabitat.BLL;
using GUHabitat.DTO;
using GUHabitat.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace GUHabitat.Controllers
{
    public class DotationCentreController : Controller
    {
        // GET: DotationCentre
        
        [HttpPost]
        public ActionResult ValiderDotationCentre(int CodeCentreDotation)
        {
            return RedirectToAction("Ajouter", new { CodeCentreDotation = CodeCentreDotation });
        }



        // GET: VenteCentre
        public ActionResult Index(string filtreMotCle, int? page)
        {

            ModelListeDotationCentre model = new ModelListeDotationCentre();
            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);
            model.filtreMotCle = filtreMotCle;
            int pageSize = 10;
            int pageIndex = page.HasValue ? page.Value : 1;
            model.ListeDotationCentre = BusinessGestionDotationCentre.Instance.ChercherListeDotationCentre(model.filtreMotCle, idEntite, login).ToPagedList(pageIndex, pageSize);

            return View(model);
        }

        public ActionResult EnInstance(int id)
        {


            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            GetUser.GetUserr(login);

            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);

            BusinessGestionDotationCentre.Instance.EnInstance(idEntite, id);

            return RedirectToAction("Index");
        }



        public ActionResult Valider(int id)
        {

            string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
            GetUser.GetUserr(login);

            int idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value);

            BusinessGestionDotationCentre.Instance.Valider(idEntite, id);


            return RedirectToAction("Index");
        }







        [HttpGet]
        public ActionResult Details(int id)
        {

            ModelAjouterDotationCentre model = new ModelAjouterDotationCentre();


            DotationCentreDto dto = BusinessGestionDotationCentre.Instance.GetDotationCentreParId(id);

            if (dto != null)
            {
                model.id = dto.id;
                model.Reference = dto.Reference;
                model.Date = dto.Date;
                model.CodeCentre = dto.CodeCentre;
                model.LibelleCentre = dto.LibelleCentre;

                model.B12 = dto.B12;
                model.B9 = dto.B9;
                model.B6R = dto.B6R;
                model.B6V = dto.B6V;
                model.B3 = dto.B3;
                model.B35 = dto.B35;

               

                model.Commentaire = dto.Commentaire;

                model.etat = dto.etat;



            };
            return View(model);

        }


        public ActionResult Ajouter(int CodeCentreDotation)
        {
            ModelAjouterDotationCentre model = new ModelAjouterDotationCentre();
            model.Date = DateTime.Now;

            string reference = GetNewCode();

            model.CodeCentre = BusinessGestionConsignationCentre.Instance.GetCentreParCode(CodeCentreDotation).Code;

            model.Reference = (reference == "1") ? "000001" : reference;

            return View(model);
        }

        [HttpPost]
        public ActionResult Ajouter(ModelAjouterDotationCentre model)
        {



            if (ModelState.IsValid)
            {

                DotationCentreDto dto = new DotationCentreDto
                {
                    idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value),

                    Reference = model.Reference,
                    Date = model.Date,
                    CodeCentre = model.CodeCentre,
                    B12 = model.B12,
                    B9 = model.B9,
                    B6R = model.B6R,
                    B6V = model.B6V,
                    B3 = model.B3,
                    B35 = model.B35,

                
                    Commentaire = model.Commentaire,

                    etat = model.etat

                };


                string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
                GetUser.GetUserr(login);



                //decimal Tonnage = (decimal)(dto.B12 * 12.5 + dto.B9 * 9 + dto.B6R * 6 + dto.B6V * 6 + dto.B3 * 3 + dto.B35 * 35) / 1000;

                //var StockActuel = BusinessGestionStatistiques.Instance.SituationInterieurParCentre(dto.CodeCentre, dto.Date, dto.Date).StockActuel;
                //if (Tonnage > StockActuel)
                //{
                //    ViewBag.MessageStockAjout = "Le Tonnage non disponible";
                //    model.Date = DateTime.Now;
                //    return View(model);
                //}


                BusinessGestionDotationCentre.Instance.Ajouter(dto);





                return RedirectToAction("Index");
            }
            else
            {
                model.Date = DateTime.Now;
                return View(model);
            }

        }



        [HttpGet]
        public ActionResult Modifier(int id)
        {

            ModelModifierDotationCentre model = new ModelModifierDotationCentre();
            model.ListeCentre = BusinessGestionDotationCentre.Instance.GetListeCentre();


            DotationCentreDto dto = BusinessGestionDotationCentre.Instance.GetDotationCentreParId(id);

            if (dto != null)
            {
                model.id = dto.id;
                model.Reference = dto.Reference;
                model.Date = dto.Date;
                model.CodeCentre = dto.CodeCentre;
                model.LibelleCentre = dto.LibelleCentre;

                model.B12 = dto.B12;
                model.B9 = dto.B9;
                model.B6R = dto.B6R;
                model.B6V = dto.B6V;
                model.B3 = dto.B3;
                model.B35 = dto.B35;

                model.Commentaire = dto.Commentaire;

                model.etat = dto.etat;



            };
            return View(model);


        }



        [HttpPost]
        public ActionResult Modifier(ModelModifierDotationCentre model)
        {


            if (ModelState.IsValid)
            {

                DotationCentreDto dto = new DotationCentreDto
                {

                    idEntite = int.Parse((User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Locality).Value),
                    id = model.id,
                    Reference = model.Reference,
                    Date = model.Date,
                    CodeCentre = model.CodeCentre,
                    LibelleCentre = model.LibelleCentre,

                    B12 = model.B12,
                    B9 = model.B9,
                    B6R = model.B6R,
                    B6V = model.B6V,
                    B3 = model.B3,
                    B35 = model.B35,

                  
                    Commentaire = model.Commentaire,

                    etat = model.etat

                };


                string login = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.NameIdentifier).Value;
                GetUser.GetUserr(login);


                //decimal Tonnage = (decimal)(dto.B12 * 12.5 + dto.B9 * 9 + dto.B6R * 6 + dto.B6V * 6 + dto.B3 * 3 + dto.B35 * 35) / 1000;

                //var StockActuel = BusinessGestionStatistiques.Instance.SituationInterieurParCentre(dto.CodeCentre, dto.Date, dto.Date).StockActuel;

                //if (Tonnage > StockActuel)
                //{
                //    ViewBag.MessageStockModifier = "Le Tonnage non disponible";

                //    model.ListeCentre = BusinessGestionConsignationCentre.Instance.GetListeCentre();
                //    model.CodeCentre = BusinessGestionConsignationCentre.Instance.GetCentreParCode(model.CodeCentre).Code;
                //    model.LibelleCentre = BusinessGestionConsignationCentre.Instance.GetCentreParCode(model.CodeCentre).libelle;

                //    model.Date = DateTime.Now;
                //    return View(model);
                //}



                BusinessGestionDotationCentre.Instance.Modifier(dto);





                return RedirectToAction("Index");
            }
            else
            {
                model.ListeCentre = BusinessGestionConsignationCentre.Instance.GetListeCentre();
                model.CodeCentre = BusinessGestionConsignationCentre.Instance.GetCentreParCode(model.CodeCentre).Code;
                model.LibelleCentre = BusinessGestionConsignationCentre.Instance.GetCentreParCode(model.CodeCentre).libelle;


                model.Date = DateTime.Now;
                return View(model);
            }

        }











        string GetNewCode()
        {

            string maxCode;
            using (var db = new DAL.GUHabitatDBEntities())
            {

                maxCode = db.DotationCentres.OrderByDescending(s => s.id).Select(x => x.Reference).FirstOrDefault();


            }

            return GetNextNumberInString(maxCode);
        }

        string GetNextNumberInString(string Number)
        {
            if (Number == string.Empty || Number == null)
                return "1";

            string str1 = "";
            foreach (Char c in Number)

                str1 = char.IsDigit(c) ? str1 + c.ToString() : "";
            if (str1 == string.Empty)
                return Number + "1";
            string str2 = str1.Insert(0, "1");
            str2 = (Convert.ToInt32(str2) + 1).ToString();
            string str3 = str2[0] == '1' ? str2.Remove(0, 1) : str2.Remove(0, 1).Insert(0, "1");

GUHabitat-Old/Views/DotationCentre/Ajouter.cshtml
@model GUHabitat.Models.ModelAjouterDotationCentre
@{
    ViewBag.Title = "";
}

<h4> <span class="badge badge-success">Centre : @Model.libelleCentreString</span></h4>

@if (ViewBag.MessageStockAjout != null)
{
    <div class="alert alert-danger">
        @ViewBag.MessageStockAjout

    </div>

}


<hr />



<form action="~/DotationCentre/Ajouter" method="post" id="form" class="form-horizontal">
    @Html.HiddenFor(x => x.id)
    @Html.HiddenFor(x => x.CodeCentre)

    <!-- Tab panes -->
    <div class="tab-content">

        <br />

        <div class="row col-12">

            <div class="row col-12">
                <h4>
                    <span class="badge badge-success">Informations Génerale</span>
                </h4>
            </div>

            <br /><br />

            <div class="row">

                <div class="form-group col-sm-4 ">
                    <label for="NniM">Reference</label>
                    @Html.TextBoxFor(x => x.Reference, new { @class = "form-control", @readonly = "true", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.Reference)
                </div>

                <div class="form-group col-sm-5 ">
                    <label for="Date"> Date </label>
                    @Html.TextBoxFor(x => x.Date, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker" })
                    @Html.ValidationMessageFor(x => x.Date)
                </div>


            </div>


        </div>


        <hr />
        <div class="row col-12">

            <div class="row col-12">
                <h4>
                    <span class="badge badge-success">Nbre Bouteilles </span>
                </h4>


            </div>


            <br /><br />


            <div class="row">



                <div class="form-group col-sm-2">
                    <label>B12</label>
                    @Html.TextBoxFor(x => x.B12, new { @class = "form-control", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.B12)
                </div>
                <div class="form-group col-sm-2">
                    <label>B9</label>
                    @Html.TextBoxFor(x => x.B9, new { @class = "form-control", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.B9)
                </div>
                <div class="form-group col-sm-2">
                    <label>B6R</label>
                    @Html.TextBoxFor(x => x.B6R, new { @class = "form-control", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.B6R)
                </div>
                <div class="form-group col-sm-2">
                    <label>B6V</label>
                    @Html.TextBoxFor(x => x.B6V, new { @class = "form-control", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.B6V)
                </div>
                <div class="form-group col-sm-2">
                    <label>B3</label>
                    @Html.TextBoxFor(x => x.B3, new { @class = "form-control", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.B3)
                </div>
                <div class="form-group col-sm-2">
                    <label>B35</label>
                    @Html.TextBoxFor(x => x.B35, new { @class = "form-control", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.B35)
                </div>

            </div>

        </div>



        <hr />



        <div class="row">
            <div class="form-group col-sm-12">
                <label for="nomFamilleM">Commentaires</label>
                @Html.TextAreaFor(x => x.Commentaire, new { @class = "form-control", @autocomplete = "off" })
                @Html.ValidationMessageFor(x => x.Commentaire)
            </div>

        </div>


        <hr />



        <br /><br />

        @if (User.IsInRole("ServiceDC"))
        {
            <div class="text-center">
                <button type="submit" class="btn btn-outline-primary ">Enregistrer</button>
            </div>
        }

    </div>
</form>
<script>
    $(function () {
        $(".datepicker").datepicker({
            dateFormat: 'dd-mm-yy',
            separator: '-',
        });
    });

    $(function () {
        $('#datetimepicker3').datetimepicker({
            dateFormat: 'HH:mm'
        });
    });





    $('form').submit(function () {
        $(this).find(':submit').attr('disabled', 'disabled');
    });





</script>

GUHabitat-Old/Views/DotationCentre/Details.cshtml
@model GUHabitat.Models.ModelAjouterDotationCentre
@{
    ViewBag.Title = "";
}

<h4> <span class="badge badge-success">Centre : @Model.LibelleCentre</span></h4>

<hr />



@if ((User.IsInRole("ServiceDC")) && (Model.etat != 3 && Model.etat != 4))
{
    <a href="@Url.Action("Modifier", "DotationCentre", new { id = Model.id })" class="btn btn-outline-primary">
        <i class="fas fa-fw fa-edit"></i>
        Modifier
    </a>
}
@if ((User.IsInRole("ServiceDC")) && (Model.etat == 2))
{
    <a class="btn btn-outline-primary" href="#" data-toggle="modal" data-target="#InstanceDotationCentre">
        <i class="fas fa-fw fa-arrow-alt-circle-left"></i>
        En Instance
    </a>

}

@if ((User.IsInRole("ServiceDC")) && (Model.etat == 1))
{
    <a class="btn btn-outline-primary" href="#" data-toggle="modal" data-target="#Valider">
        <i class="fas fa-check"></i>
        Valider
    </a>

}



<form action="~/DotationCentre/Ajouter" method="post" id="form" class="form-horizontal">
    @Html.HiddenFor(x => x.id)
    @Html.HiddenFor(x => x.CodeCentre)

    <!-- Tab panes -->
    <div class="tab-content">

        <br />

        <div class="row col-12">

            <div class="row col-12">
                <h4>
                    <span class="badge badge-success">Informations Génerale</span>
                </h4>
            </div>

            <br /><br />

            <div class="row">

                <div class="form-group col-sm-4 ">
                    <label for="NniM">Reference</label>
                    @Html.TextBoxFor(x => x.Reference, new { @class = "form-control", @readonly = "true", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.Reference)
                </div>

                <div class="form-group col-sm-5 ">
                    <label for="Date"> Date </label>
                    @Html.TextBoxFor(x => x.Date, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.Date)
                </div>


            </div>


        </div>


        <hr />
        <div class="row col-12">

            <div class="row col-12">
                <h4>
                    <span class="badge badge-success">Nbre Bouteilles</span>
                </h4>


            </div>


            <br /><br />


            <div class="row">



                <div class="form-group col-sm-2">
                    <label>B12</label>
                    @Html.TextBoxFor(x => x.B12, new { @class = "form-control", @autocomplete = "off", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.B12)
                </div>
                <div class="form-group col-sm-2">
                    <label>B9</label>
                    @Html.TextBoxFor(x => x.B9, new { @class = "form-control", @autocomplete = "off", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.B9)
                </div>
                <div class="form-group col-sm-2">
                    <label>B6R</label>
                    @Html.TextBoxFor(x => x.B6R, new { @class = "form-control", @autocomplete = "off", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.B6R)
                </div>
                <div class="form-group col-sm-2">
                    <label>B6V</label>
                    @Html.TextBoxFor(x => x.B6V, new { @class = "form-control", @autocomplete = "off", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.B6V)
                </div>
                <div class="form-group col-sm-2">
                    <label>B3</label>
                    @Html.TextBoxFor(x => x.B3, new { @class = "form-control", @autocomplete = "off", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.B3)
                </div>
                <div class="form-group col-sm-2">
                    <label>B35</label>
                    @Html.TextBoxFor(x => x.B35, new { @class = "form-control", @autocomplete = "off", @readonly = "true" })
                    @Html.ValidationMessageFor(x => x.B35)
                </div>

            </div>

        </div>



        <hr />


        <div class="row">
            <div class="form-group col-sm-12">
                <label for="nomFamilleM">Commentaires</label>
                @Html.TextAreaFor(x => x.Commentaire, new { @class = "form-control", @autocomplete = "off", @readonly = "true" })
                @Html.ValidationMessageFor(x => x.Commentaire)
            </div>

        </div>


        <hr />



        <br /><br />

        @if (User.IsInRole("ServiceDC"))
        {
            <div class="text-center">
                <button type="submit" class="btn btn-outline-primary ">Enregistrer</button>
            </div>
        }

    </div>
</form>


<!-- EnInstance Modal-->
<div class="modal fade" id="InstanceDotationCentre" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Etês vous sûre de vouloir mettre En Instance cet document?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>

                <a href="@Url.Action("EnInstance","DotationCentre", new { id = Model.id})" class="btn btn-primary">
                    En Instance
                </a>
            </div>
        </div>
    </div>
</div>


<!-- Valider Modal-->
<div class="modal fade" id="Valider" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Etês vous sûre de vouloir Valider cet document?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>

                <a href="@Url.Action("Valider","DotationCentre", new { id = Model.id})" class="btn btn-primary">
                    Valider
                </a>
            </div>
        </div>
    </div>
</div>




<script>
    $(function () {
        $(".datepicker").datepicker({
            dateFormat: 'dd-mm-yy',
            separator: '-',
        });
    });

    $(function () {
        $('#datetimepicker3').datetimepicker({
            dateFormat: 'HH:mm'
        });
    });





    $('form').submit(function () {
        $(this).find(':submit').attr('disabled', 'disabled');
    });





</script>

GUHabitat-Old/Views/DotationCentre/Index.cshtml
@using PagedList.Mvc
@{
    ViewBag.Title = "Liste Dotation Centre";
}
@model GUHabitat.Models.ModelListeDotationCentre
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@if (TempData["SuccessMessage"] != null)
{
    <span style="color:green;">@TempData["SuccessMessage"] </span>
}
@if (TempData["ErrorMessage"] != null)
{
    <span style="color:red;">@TempData["ErrorMessage"] </span>
}
<br />
<br />
<div>
    <form class="form-inline" action="~/DotationCentre/Index">
        <div class="magin"></div>
        <div class="form-group left ">

            @Html.TextBoxFor(x => x.filtreMotCle, new { @class = "form-control left", @autocomplete = "off", @placeholder = "Mot Clé" })&ensp;

        </div>
        <div class="form-group right ">
            <button type="submit" class="btn btn-primary right" id="buttonChercher">Chercher</button>
        </div>
    </form>
    <br />
    <div id="divAjaxContainer">
        <div class="table-responsive">

            <table class="table table-bordered table-hover">
                <thead class="section-colored alert-success">
                    <tr>
                        <th class="text-lg-center">Référence</th>
                        <th class="text-lg-center">Date</th>
                        <th class="text-lg-center">Code</th>
                        <th class="text-lg-center">Centre</th>
                        <th class="text-lg-center">B12</th>
                        <th class="text-lg-center">B09</th>
                        <th class="text-lg-center">B6R</th>
                        <th class="text-lg-center">B6V</th>
                        <th class="text-lg-center">B03</th>
                        <th class="text-lg-center">B35</th>

                        <th class="text-lg-center">Etat</th>
                        <th class="text-lg-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ListeDotationCentre)
                    {
                    <tr>
                        <td class="text-lg-center">@item.Reference</td>
                        <td class="text-lg-center">@item.Date.ToShortDateString()</td>
                        <td class="text-lg-center">@item.CodeCentre </td>
                        <td class="text-lg-center">@item.LibelleCentre </td>
                        <td class="text-lg-center">@item.B12</td>
                        <td class="text-lg-center">@item.B9</td>
                        <td class="text-lg-center">@item.B6R</td>
                        <td class="text-lg-center">@item.B6V</td>
                        <td class="text-lg-center">@item.B3 </td>
                        <td class="text-lg-center">@item.B35 </td>
                        <td class="text-lg-center">@item.etatString </td>

                        <td class="text-lg-center">
                            <a href="@Url.Action("Details","DotationCentre", new { id = item.id})" class="btn btn-outline-info">
                                <i class="fas fa-fw fa-info-circle"></i>
                                Details
                            </a>

                        </td>



                    </tr>
                    }

                </tbody>

            </table>

        </div>




        <div class="pager">
            Page @(Model.ListeDotationCentre.PageCount < Model.ListeDotationCentre.PageNumber ? 0 : Model.ListeDotationCentre.PageNumber)
            / @Model.ListeDotationCentre.PageCount   @Html.PagedListPager(Model.ListeDotationCentre, page => Url.Action("Index", new { page, filtreMotCle = Model.filtreMotCle }))
        </div>
    </div>

</div>





@*<script>
        $(document).ready(function () {
            toastr.success("Test");
        });
    </script>*@

GUHabitat-Old/Views/DotationCentre/Modifier.cshtml
@model GUHabitat.Models.ModelModifierDotationCentre
@{
    ViewBag.Title = "";
}

<h4> <span class="badge badge-success">Centre : @Model.LibelleCentre</span></h4>

@if (ViewBag.MessageStockModifier != null)
{
    <div class="alert alert-danger">
        @ViewBag.MessageStockModifier

    </div>
}

<hr />



<form action="~/DotationCentre/Modifier" method="post" id="form" class="form-horizontal">
    @Html.HiddenFor(x => x.id)

    <!-- Tab panes -->
    <div class="tab-content">

        <br />

        <div class="row col-12">

            <div class="row col-12">
                <h4>
                    <span class="badge badge-success">Informations Génerale</span>
                </h4>
            </div>

            <br /><br />

            <div class="row">

                <div class="form-group col-sm-4 ">
                    <label for="NniM">Reference</label>
                    @Html.TextBoxFor(x => x.Reference, new { @class = "form-control", @readonly = "true", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.Reference)
                </div>

                <div class="form-group col-sm-5 ">
                    <label for="Date"> Date </label>
                    @Html.TextBoxFor(x => x.Date, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker" })
                    @Html.ValidationMessageFor(x => x.Date)
                </div>

                <div class="form-group col-sm-3 ">
                    <label for="Entite">Centre</label>
                    @Html.DropDownListFor(x => x.CodeCentre, new SelectList(Model.ListeCentre, "Code", "libelle"), "--Choix Centre --", new { @class = "form-control", @id = "Centre" })
                    @Html.ValidationMessageFor(x => x.CodeCentre)
                </div>

            </div>


        </div>


        <hr />
        <div class="row col-12">

            <div class="row col-12">
                <h4>
                    <span class="badge badge-success">Nbre Bouteilles</span>
                </h4>


            </div>

            <br /><br />


            <div class="row">



                <div class="form-group col-sm-2">
                    <label>B12</label>
                    @Html.TextBoxFor(x => x.B12, new { @class = "form-control", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.B12)
                </div>
                <div class="form-group col-sm-2">
                    <label>B9</label>
                    @Html.TextBoxFor(x => x.B9, new { @class = "form-control", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.B9)
                </div>
                <div class="form-group col-sm-2">
                    <label>B6R</label>
                    @Html.TextBoxFor(x => x.B6R, new { @class = "form-control", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.B6R)
                </div>
                <div class="form-group col-sm-2">
                    <label>B6V</label>
                    @Html.TextBoxFor(x => x.B6V, new { @class = "form-control", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.B6V)
                </div>
                <div class="form-group col-sm-2">
                    <label>B3</label>
                    @Html.TextBoxFor(x => x.B3, new { @class = "form-control", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.B3)
                </div>
                <div class="form-group col-sm-2">
                    <label>B35</label>
                    @Html.TextBoxFor(x => x.B35, new { @class = "form-control", @autocomplete = "off" })
                    @Html.ValidationMessageFor(x => x.B35)
                </div>

            </div>

        </div>



        <hr />

        <div class="row">
            <div class="form-group col-sm-12">
                <label for="nomFamilleM">Commentaires</label>
                @Html.TextAreaFor(x => x.Commentaire, new { @class = "form-control", @autocomplete = "off" })
                @Html.ValidationMessageFor(x => x.Commentaire)
            </div>

        </div>


        <hr />



        <br /><br />

        @if (User.IsInRole("ServiceDC"))
        {
            <div class="text-center">
                <button type="submit" class="btn btn-outline-primary ">Enregistrer</button>
            </div>
        }

    </div>
</form>
<script>
    $(function () {
        $(".datepicker").datepicker({
            dateFormat: 'dd-mm-yy',
            separator: '-',
        });
    });

    $(function () {
        $('#datetimepicker3').datetimepicker({
            dateFormat: 'HH:mm'
        });
    });





    $('form').submit(function () {
        $(this).find(':submit').attr('disabled', 'disabled');
    });


    document.getElementById("Centre").value  = @Model.CodeCentre;


</script>